# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"
issues:
  max-same-issues: 0
linters:
  # disable:
  # - all
  enable:
  - durationcheck
  - errcheck
  - copyloopvar
  - forcetypeassert
  - godot
  # - gosimple
  - ineffassign
  - makezero
  - misspell
  - nilerr
  - predeclared
  - staticcheck
  # - tenv
  - unconvert
  - unparam
  - unused
  - govet
formatters:
  enable:
  - gci
  - gofmt
  - gofumpt
  - goimports
  - golines
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'
